- hosts: all
  tags: jenkins
  tasks:
    - name: Install Java 8
      yum:
        name: "java-1.8.0-openjdk"
        state: present
      become: true

    - name: Correct the alternatives to change default Java version.
      become: true
      alternatives:
        name: java
        link: /usr/bin/java
        path: "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.144-0.b01.el7_4.x86_64/jre/bin/java"

    - name: Download Jenkins Repo
      get_url:
        url: "https://pkg.jenkins.io/redhat/jenkins.repo"
        dest: /etc/yum.repos.d/jenkins.repo
      become: true

    - name: Import GPG Key
      become: true
      rpm_key:
        state: present
        key: "https://pkg.jenkins.io/redhat/jenkins.io.key"

    - name: Install Jenkins
      become: true
      yum:
        name: jenkins
        state: present

    - name: Change Jenkins Java Options
      lineinfile:
        dest=/etc/sysconfig/jenkins
        regexp=^JENKINS_JAVA_OPTIONS=
        line=JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"
      become: true

    - name: Start & Enable Jenkins
      become: true
      service:
        name: jenkins
        state: started
        enabled: yes
