Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.network "private_network", ip: "10.10.10.1"

  config.vm.provision "ansible" do |ans|
    ans.playbook = "playbook.yml"
  end
end
